### ISSUE TITLE
GetLogicalProcessors misuses SYSTEM_CPU_SET_INFORMATION

### ISSUE THREAD

**Issue by CookiePLMonster** [GameTechDev/HybridDetect#1]
In the docs for [SYSTEM_CPU_SET_INFORMATION ](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-system_cpu_set_information), MSDN expressly says:
> This is a variable-sized structure designed for future expansion. When iterating over this structure, use the size field to determine the offset to the next structure.

However, the way `GetLogicalProcessors` iterates through the data returned from `GetSystemCpuSetInformation` completely disregards this note:
https://github.com/GameTechDev/HybridDetect/blob/1a997834253d740492b1689ae365136c86c66686/HybridDetectConsole/HybridDetect.h#L389-L392

While this code works now (although `offset + sizeof(SYSTEM_CPU_SET_INFORMATION) <= size` looks really weird to me and I don't understand the intentions behind it!), it will break if Microsoft ever decides to do as they say and expand this structure.

For an example of proper usage of this data, see:
https://github.com/Cxbx-Reloaded/Cxbx-Reloaded/blob/5e42d181f2daf4a244450b1535223d4c71ea5e54/src/common/win32/Threads.cpp#L116-L127

Strangely enough, the code snippet does adhere to the need of checking a `Type` field to ensure the data accessed is valid, so the only issue here is the misuse of size.

**Comment by MarissaDuBois-Intel** [comment]
HI there, I just pushed a change to use the sizes correctly. Not sure what I was thinking with that original implementation, thanks for finding the bug. 

https://github.com/GameTechDev/HybridDetect/commit/7e99fd2a69dfda56699e8fdc706233a4a59979ec

**Comment by CookiePLMonster** [comment]
Thanks for getting to it so quickly! Everything looks good now as far as I can tell 😄

EDIT: Except for the Dev Guide
https://www.intel.com/content/www/us/en/developer/articles/guide/alder-lake-developer-guide.html
but I don't know if it's going to be updated separately or automatically.

**Comment by MarissaDuBois-Intel** [comment]
I will need to work on getting the dev guide update separately, it needs to go through a process.
